"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Point_1 = require("./Point");
var TroisPoints_1 = require("./TroisPoints");
var A = new Point_1.Point(1, 2);
var B = new Point_1.Point(2, 4);
var C = new Point_1.Point(3, 6);
var AB = A.CalculerDistance(B);
console.log("Distance AB : " + AB);
var AC = A.CalculerDistance(C);
console.log("Distance AC : " + AC);
var BC = B.CalculerDistance(C);
console.log("Distance BC : " + BC);
var milieuAB = A.calculerMilieu(B);
console.log("Milieu de AB : (" + milieuAB.getabs() + ", " + milieuAB.getord() + ") ");
var milieuAC = A.calculerMilieu(C);
console.log("Milieu de AC : (" + milieuAC.getabs() + ", " + milieuAC.getord() + ") ");
var milieuBC = B.calculerMilieu(C);
console.log("Milieu de BC : (" + milieuBC.getabs() + ", " + milieuBC.getord() + ") ");
var triangle = new TroisPoints_1.TroisPoints(A, B, C);
var isIsocele = triangle.EstIsocele();
console.log("Le triangle est isocèle ? " + isIsocele);
var estAligné = triangle.TesterAlignement();
console.log("Les points sont alignés ? " + estAligné);
